### ISSUE TITLE
NSFDbLocalSecInfoGet - get details from HCL about function.

### ISSUE THREAD

**Issue by dpastov** [prominic/encryptNTF#1]
@JustinProminic we need to contact HCL to get details about function

`NSFDbLocalSecInfoGet`

I tried many different combinations but it always crash my client/server.

**Comment by JustinProminic** [comment]
Hi @dpastov -- yes please feel free to communicate directly with "John Paganetti" <john.paganetti@pnp-hcl.com> on the thread we have going.  The last activity I have on that thread in my inbox was from 12/29/2019 10:39 AM US CT for reference.

**Comment by dpastov** [comment]
@JustinProminic Get function is still a unknown thing for us therefore I will send another email during the week to HCL asking them same questions you asked last time.

**Comment by dpastov** [comment]
@JustinProminic the instruction from John did not work. I will send an email today with my tests results.

**Comment by dpastov** [comment]
@JustinProminic it's ready. I will send results tomorrow morning.
