### ISSUE TITLE
NSFDbLocalSecInfoSet - not working as described by HCL

### ISSUE THREAD

**Issue by dpastov** [prominic/encryptNTF#2]
@JustinProminic I sent you an email few days ago, but switching to github now so we keep thread here.

We need some help for points 2 and 3.

here are my tests results with NSFDbLocalSecInfoSet (Domno 9.01 FP4, Windows 10, Notes Client 9.01 FP10)

1) Clearing out the encryption setting (option=2) - works as expected.
Example:
rc = NSFDbLocalSecInfoSet(hDb, 2, 0, "") - that works.

2) Setting up encryption on a new db (option=1) - does not work & corrupt database.
Example:
rc = NSFDbLocalSecInfoSet(hDb, 1, 3, "") - once we execute such line we will corrupt database and also get a message:

[4350:0004-01AC] Hardware/OS error (The specified encryption method is invalid or not supported by this version of software) reading from database (C:\IBM\Domino\data\test2.nsf), Length=16 (PID=4350/TID=4)

3) Modify the existing encryption setting (option=3) - nothing happens.
Example:
rc = NSFDbLocalSecInfoSet(hDb, 3, 2, "")

**My suggestions/questions**

4) Can we get in touch with HCL? It's odd that we by luck managed to set encryption (option=0) that John did not mentioned, so I am pretty sure the function works but maybe we miss some information. Remember that in my first example we were able to set encryption using such line:
Example
rc = NSFDbLocalSecInfoSet(hDb, 0, 1, "")

5) Ask them why points 2) and 3) do not work (I can write email myself if you allow that).

**Comment by JustinProminic** [comment]
Hi @dpastov -- yes please feel free to communicate directly with "John Paganetti" <john.paganetti@pnp-hcl.com> on the thread we have going.  The last activity I have on that thread in my inbox was from 12/29/2019 10:39 AM US CT for reference.

**Comment by dpastov** [comment]
@JustinProminic I have updated repo with latest changes from HCL.
We are more/less satisfied with how function NSFDbLocalSecInfoSet works.

We can now:
- set encryption on database (require compact after all)
- remove encryption  (require compact after all)

What we miss is - get function (there is another ticket for that).

**Comment by dpastov** [comment]
@JustinProminic we can set/remove encryption option (require to run compact after that).
